-- DAEMS Oracle 19c Schema Creation Script

-- Drop existing tables (optional, use with caution)
-- DROP TABLE predictions;
-- DROP TABLE resources;
-- DROP TABLE volunteers;
-- DROP TABLE incidents;
-- DROP TABLE users;

-- Users table for Admin access
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(100) NOT NULL,
    role VARCHAR2(20) DEFAULT 'admin'
);

-- Incidents table (mapped from CSV + frontend needs)
CREATE TABLE incidents (
    incident_id VARCHAR2(50) PRIMARY KEY,
    type VARCHAR2(100),
    title VARCHAR2(255),
    description CLOB,
    severity VARCHAR2(20), -- critical, high, medium, low
    location VARCHAR2(255),
    latitude NUMBER,
    longitude NUMBER,
    incident_date DATE,
    incident_time VARCHAR2(20),
    resources_allocated NUMBER DEFAULT 0,
    volunteers_allocated NUMBER DEFAULT 0,
    status VARCHAR2(20) DEFAULT 'active' -- active, contained, monitoring
);

-- Volunteers table
CREATE TABLE volunteers (
    volunteer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    skills VARCHAR2(255),
    location_dist VARCHAR2(50),
    status VARCHAR2(20) DEFAULT 'available', -- available, deployed
    avatar_init VARCHAR2(5)
);

-- Resources table
CREATE TABLE resources (
    resource_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    current_stock NUMBER,
    max_stock NUMBER,
    unit VARCHAR2(20),
    critical_threshold NUMBER
);

-- Predictions table
CREATE TABLE predictions (
    prediction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR2(100),
    confidence NUMBER,
    timeframe VARCHAR2(50),
    conditions VARCHAR2(255),
    location VARCHAR2(255),
    severity VARCHAR2(20),
    latitude NUMBER,
    longitude NUMBER
);

-- Insert default admin
INSERT INTO users (username, password) VALUES ('admin', '1234');

-- Sample Resources (matching App.jsx)
INSERT INTO resources (name, current_stock, max_stock, unit, critical_threshold) VALUES ('Medical Kits', 12, 50, 'units', 15);
INSERT INTO resources (name, current_stock, max_stock, unit, critical_threshold) VALUES ('Water Supply', 8, 100, 'kL', 20);
INSERT INTO resources (name, current_stock, max_stock, unit, critical_threshold) VALUES ('Emergency Fuel', 340, 500, 'L', 100);
INSERT INTO resources (name, current_stock, max_stock, unit, critical_threshold) VALUES ('Rescue Vehicles', 3, 10, 'units', 3);
INSERT INTO resources (name, current_stock, max_stock, unit, critical_threshold) VALUES ('Food Rations', 45, 200, 'packs', 40);
INSERT INTO resources (name, current_stock, max_stock, unit, critical_threshold) VALUES ('Tents/Shelter', 28, 80, 'units', 20);

COMMIT;
